label hinata_date1:
    scene bg schoolfront
    show hat
    k "(I think I’ll text Hinata. She seemed like a nice person.)"
    "*abababa* *abababa*"
    h "Hello, who is it?"
    #{Play https://www.youtube.com/watch?v=Jqv3No98j5M }
    k "It’s me, Keikumusume, from the mahjong club. I was wondering if you’d like to hang out after school today. We don’t have club on, after all."
    h "Ah, this is perfect timing! I actually need some help with the school garden. Would you be able to come on down right now?"
    k "I’d be happy to!"
#    {BG transition to school garden}
    scene bg schoolgarden
    show hinata at right1
    h "I’m so glad you stopped by. Would you be able to help me pick up that big bag of mulch over there?"
    show hat at left1
    k "Oh, sure."
    k "1, 2, 3!"
    k "(What the hell, even with two people this is so heavy!)"
    k "(Just moving it this short distance is a pain in the backside.)"
#    {Play some sort of thud sound effect for the sound of the mulch bag being dropped}
    k "Phew. Shouldn’t this be a job for the boys in your club?"
    h "Club? There’s no club. It’s actually just me."
    k "Wait really? You do all this by yourself?"
    k "(I never really noticed it before, but these school gardens are actually really extensive.)"
    k "(There’s some gorgeous hydrangeas, mushroom boxes, rows of vegetables and berries, a patch of lavender, and even a rose bush.)"
    h "Well, I wouldn’t say it’s all me. Of course nature does a lot of the work on its own."
    k "That’s still really incredible though."
    h "I do appreciate hearing that. Although I honestly think it could be a lot better."
    h "For example, I’d like to grow melons. Big juicy melons."
    h "But doing that really isn’t feasible on my own. It requires a lot of soil work to grow watermelons."
    h "They need lots of mulching, raised beds, and constant watering."
    h "I feel limited, because I can only do so much on my own."
    h "Like these flowers right here. The poor things are starting to wilt because I’ve gotten a little slack in watering them."
    k "I see. Well I can help out for today at least. Let’s give it our all."
#    {fade bg to black, into sunset shool garden.}
    k "(Me and Hinata both worked hard.)"
    k "(Although honestly I feel like all I really did was carry stuff. I really don’t know what I’m doing when it comes to garden stuff.)"
    k "(Every movement she makes with the plants looks so precise. It’s like she knows the exact correct distance to put between seeds when she puts them into the soil.)"
    k "(The way she gently pats the soil down on top of them, it’s like she’s taking care of a baby.)"
    h "It’ll be getting dark soon. So I think we’ve done enough..."
    k "(Finally. Doesn’t this girl get tired?)"
    k "So what did we actually accomplish today? Come to think of it, I never asked what we were planting."
    h "Strawberries. Once they’ve finished growing I’ll share them all with the club."
    h "You’ve been a big help today. I wouldn’t have been able to plant anywhere near as many as we did if you weren’t around."
    k "I feel like I was just the muscle, but I don’t mind."
    k "How’d you get so into gardening anyway?"
    k "For some reason, at first glance I got more of an artist vibe from you."
    h "Everyone always says that and I don’t understand why. Maybe it’s the beret?"
    h "Anyway, my house has a big backyard in it. My parents are often away on business trips and stuff, so I didn’t have a whole lot to do on holidays."
    h "So I did gardening work. I’d set myself projects and stuff, and I’d pass the weeks watching the plants grow."
    k "Couldn’t you have just like, watched movies or something? What was the appeal?"
    h "I guess it’s the satisfaction of watching something grow. Raising a tiny seed into a fully grown plant and knowing that it lives because you nurtured it."
    h "Cooking also tastes better when you’re using your own herbs and stuff too."
    h "I think if you did a blind taste test or something like that, I wouldn’t notice the difference. But when you’ve put hard work into something, the payoff is made a lot sweeter."
    k "I see, I see. I can definitely see the appeal of gardening now."
    h "It always used to shock my parents whenever they came home and they saw how big the plants had gotten."
    h "A tiny seed growing into a fully sized plant in the blink of an eye."
    k "Yeah that does sound kind of shocking. Like if you just left a seed and came back a little bit later and there was a fully grown tree in the empty space there. That’d be weird."
    k "Anyway, thanks for letting me help out. It was a lot of fun."
    h "Mhm. I’ll be sure to give you a big share of the strawberries. See you tomorrow!"
    hide hinata
#    {BG scene transition to Keikumusumes room, night, play the crickets noises. https://www.youtube.com/watch?v=Olfg9KK_bmE}
#        {same as above.}
    scene bg keikunight
    show hat
    k "(I didn’t realise gardening could be so enjoyable.)"
    k "(I didn’t think it could be so tiring either.)"
    k "(Whenever I walked past the gardens at school, I just sort of took them for granted.)"
    k "(But if it weren’t for her maintaining it all, the school grounds would look a lot more barren.)"
    k "(I guess there’s a lot of things like that in this world. Hard work that fades into the background and gets ignored.)"
    k "(She deserves a little more recognition.)"
    k "(Hinata seems like a nice girl. I want to pick those strawberries we planted together soon.)"
    k "(. . .)"
    k "( z z z )"
    jump post_date1


label hinata_date2:
    show hat
    k "(Off to the gardens then.)"
    scene bg garden
#    {play https://www.youtube.com/watch?v=2DuvYC3zENI /// is this good? I’m not sure. Does it fit the somewhat melancholy conversation they’re having?}
#        {it should be good enough}
    show hat at left1
    k "Hey, Hinata."
    show hinata at right1
    h "Hello, Keiku. Did you want to go anywhere in particular this afternoon?"
    k "Not really. I was just bored and I thought you might need help with the plants again."
    h "Ah thanks, I really appreciate the help."
    h "But I’m not actually doing any garden work today. I’ve been doing photography instead. Although I can just do that later if you’re not interested in it."
    k "Nah, it sounds interesting. What sort of photography is it?"
    h "Nature photography. I guess you could say it’s like my third hobby, after mahjong and gardening."
    k "I see. How’d you get into photography then, and mahjong for that matter."
    h "Well, my family used to play a lot of mahjong. I already knew the rules and I had to join a club, so I joined the mahjong club and that was that."
    h "In regards to photography, I think that’s just a natural extension of gardening."
    h "The self-satisfaction from growing a beautiful flower bed is nice, but being able to share it with others is even better."
    h "It’s nice seeing your work get featured too."
    k "Wow, your photography has been featured? Like in a magazine?"
    h "Yep. Although that only happened a few times."
    h "When I was really young, I managed to get the perfect nature shot."
    h "It was a shot of a crested ibis taking off. I don’t know if you’ve ever seen one, but when they open their wings, they have the most beautiful orange feathers on the inside of their wingspan."
    h "But because it’s on the inside of their wings, you can only see this when they’re just about to take off, or in flight."
    h "I got really lucky. It had wandered into a local pond, probably in search of frogs to eat."
    h "I just happened to get the perfect shot of it getting ready to take off. I didn’t even have to adjust the camera settings or anything. It was like the stars had aligned for me to get that photo."
    h "I submitted it to a local nature magazine, and they put it right on the front page."
    h "My parents were so proud of me. Right after that they went out and bought me a fancy camera and told me that I had a big future in photography. I remember the magazine said that I might be a prodigy."
    h "But it was all just luck in the end, haha."
    h "I’ve been chasing shots like that ever since then. But none of them have turned out quite like that shot."
    h "I would occasionally make it into the back pages of the local nature magazine, but never the front cover or anything like that again."
    h "Honestly, it kind of annoys me."
    k "Yeah, I can imagine so."
    k "I had something kind of similar happen to me."
    k "When I was really young, I was very far ahead of the rest of my class in reading and writing."
    k "I remember feeling really good about it, because the teachers would always praise me a lot."
    k "They’d say things like ‘Oh Keikumusume, when you get older you’re going to be an amazing writer!’"
    k "I’d send in stories to the local kids writing competitions and I’d win every time."
    k "But when I got older, the competition got a lot tougher."
    k "There wasn’t really any room for writing stories in the upper levels of school either. It was all just essays all the time."
    k "There was the literature club of course. But the only other member in it didn’t actually care for literature. He just showed up and played video games while I read and wrote my dumb short stories in silence."
    h "Yeah, that definitely sounds like what I feel. When you’re a kid and you show a little talent at something, they praise you and expect you to become a master at it."
    h "But really I just peaked early and I’m not going any higher."
    h "Sometimes I wonder if I disappointed anyone. Although I don’t think I’m important enough for anyone to have placed that much stock in me in the first place."
    k "That’s a really sad way of looking at things. I definitely feel similarly though."
    k "But there’s no use thinking about the past. We shouldn’t be focusing on what people thought we would be."
    h "Yeah, I guess you’re right. It’s probably fine to just be okay at photography if that’s all I can do."
    k "Well, it’s not like we shouldn’t push ourselves to be the best we can be. We just shouldn’t compare ourselves to the unrealistic expectations of adults."
    h "That’s exactly right. I have other things to do anyway, like gardening."
    k "That’s right. I’m actually pretty lucky that my uncle passed his title of mahjong detective onto me. If he didn’t do that, I don’t know what the heck I’d do after I graduate."
    k "Even if I can’t make a living as a writer, at least I’m guaranteed a job as a crummy detective."
    h "Hehe, that’s right. People will always need food too. So gardening will definitely be in demand."
    k "Yep, you got it. We already have our fallback options in place."
    h "Maybe we should go start a farm somewhere."
    k "That sounds comfy, but I don’t think there’s anything I could contribute to a farm."
    h "Oh don’t worry about that. I’m sure there’ll be a ‘mysterious case of the missing eggs’ or something for you to solve."
    k "Heh, that’d feel a lot less high pressure than another murder case."
    k "Although in this property market, I don’t think we’re going to be able to afford any farming land anytime soon."
    h "Ah, that’s true. Reality is such a drag."
    k "Anyway, do you mind if I see some of your photos?"
    h "Oh sure. Here’s my phone. There’s a folder in there of what I consider to be some of my best shots."
    k "Hmmhmm."
    k "(Oh, this one here is quite good. The morning dew on these red leaves looks so pretty.)"
    k "(This next one is a little gruesome. It’s a shot of a fly stuck in a venus fly trap.)"
    k "(There’s a certain rawness to it though. You can see the fly’s leg sticking out, like it’s trying to pry the bars open.)"
    k "(Even though it’s a disgusting fly, you still kind of want to cheer it on.)"
    k "(The next photo here is really good. It’s a fox sticking its head out of a creek.)"
    k "(The way the fox’s head is just barely sticking out of the water is interesting. It’s like it’s trying to keep a low profile, to sneak up on someone.)"
    k "(Maybe it’s hunting something?)"
    k "(All these photos are actually pretty good.)"
    k "Hinata, I think you’re underestimating yourself a little."
    h "Hmm? What do you mean?"
    k "While it’s true that the photo you took of the ibis might have been a fluke, that doesn’t invalidate the quality of these photos."
    k "When you think about it, taking a photo that’s good enough to get into a magazine is pretty impressive on its own, right?"
    k "So I don’t think it’s worthwhile getting at all hung up on whether or not it’s good enough for the front page or just the backpages."
    h "Hmmm. Well, it is true that not just any ordinary photo can make it into a magazine."
    h "But I guess after the first time it happened, I’m just craving that feeling again."
    h "Being acknowledged like that is a really good feeling. It’s like you’re on top of the world."
    h "Oh well. There’s nothing more to it than to do my best."
    k "That’s right."
    scene bg gardens
    show hat at left1
    k "(Ah, she took a lot of photos.)"
    k "(She sure can talk for a long time if you ask her about all the plants she has hanging around here.)"
    k "(It’s not like I don’t enjoy listening to it though.)"
    show hinata at right1
    h "It’s starting to get late. I think now’s a good time to go home."
    k "Yeah, I should probably be heading off soon."
    k "Thanks for having me here and letting me look through all your photos, Hinata."
    h "No, thank you for coming out here. I really enjoy having you around the garden."
    h "Even though I’ve only known you for a few days, I feel like I can relax around you."
    k "I feel the same way. Anyway, I’ll see you tomorrow at the tournament."
    h "Yep. See you tomorrow!"
    scene bg keikunight
    show hat
    k "That was a nice afternoon."
    k "It felt good to confide in someone like that."
    k "(Despite meeting her just a few days ago, it really does feel like Hinata is someone who I can trust.)"
    k "(I feel like we’re similar in a way. Maybe you could say we’re like two peas in a pod?)"
    k "(Anyway, time for bed. Gotta be well rested for that tournament.)"
    k "(I don’t want to be the girl who deals into an open daisangen.)"
    k "(. . .)"
    k "( z z z )"
    jump post_date2
