label nana_date1:
    scene bg schoolfront
    show hat

    k "(Nana seemed like a fun person to be around. I’ll call and ask her if she wants to hang out.)"
    "* abababa* *abababa*"

    n "Yo! Who’s this?"
    k "Oh, it’s me, Keikumusume."
    n "Ah, the new girl! What’s up?"
    k "Well, I’ve got nothing on tonight, so I was wondering if you’d want to hang out."
    n "You’ve called with great timing."
    n "I was actually planning on doing some fencing, but my usual partner for that is away sick today."
    n "Until you called up I wasn’t sure if I was going to be able to do it today."
    n "Meet me in the gym asap!"
    k "(Wait, fencing? Isn’t that the sport with the swords? I didn’t think she would just invite me to something like that right off the bat.)"
#    {bg change to the gym. Consider having hat png and nana png with png fencing masks over their faces and (blunted sport) fencing blades, mite b funny}
#    {Play https://files.catbox.moe/i91fhx.ogg }
    hide hat
    scene bg gym
    show hatfence at left1
    show nanafence at right1
    n "Keiku, have you ever done this before?"
    k "Nope. I don’t know the rules at all. What am I meant to be doing here?"
    n "It’s simple. You just try to hit the other person with the end of the blade."
    k "How do you tell when a point is scored?"
    n "Each blade has a button on the end of it. When it gets pushed against another person, it plays a big buzzer sound."
    k "Isn’t this dangerous? Aren’t there safety precautions or something that we should be going over?"
    n "Nah. Look, they bend to soften the impact. Totally harmless."
    n "First to ten points wins. Get ready!"
#    {play schwing sound effect, then buzzer.}
    n "Point one to me~"
    k "(S-she’s fast!)"
#    {Play clank then schwing sound effect}
    n "Nice work! You’ve only just started, but you already figured out what a parry is. Although you’re still a little too slow."
    k "(Damnit, when she talks like that, I really want to beat her!)"
#    {Play continuous sword clanging noises}
    k "(Kgh, she’s so fast!)"
    k "(But I’m starting to get the hang of this. I can keep up with her!)"
#    {Play BZZT sound}
    k "(Ah! She got me again!)"
    n "Honestly, you’re learning pretty quick. You only just started, but it looks like you’ve intuitively worked out the proper way to space your feet already."
#    {Moar sword noises}
#    {BZZT}
#    {BZZT}
#    {BZZT}
#    {BZZT}
#    {BZZT}
#    {BZZT}

    k "(She keeps complimenting me whenever she scores, but I can’t get a hit on her at all.)"
    k "(I’m not sure if that’s encouraging or just annoying.)"
    k "(I think that there’s only one way I’m going to get a hit on her...)"
    k "(...and that’s to engage in some unconventional tactics!)"
    n "Are you ready? This will finish it off!"
    k "(Here she comes, she’s charging in like usual…)"
    k "Nana, behind you, WATCH OUT!"
    n "Huh?"
    k "Gotcha!"
#    {BZZT}
    k "(I can’t believe that worked!)"
    n "Aaaaaa, I can’t believe I fell for that. What a dirty trick."
    k "Sorry, is that frowned upon in fencing? Can’t blame a novice for not knowing."
    n "Hehe, that’s fine. All’s fair in love and war after all."
    n "9-1! Next bout! Go!"
    k "(I doubt that last technique is going to work again, but there’s still no way I’ll be able to take her head on.)"
    k "(I can see how she attacks now. She always points high! Like she’s aiming for the head.)"
    k "(I think it’s called a lunge? When she leaps forwards with her arm outstretched, like a scorpion stinging its prey.)"
    k "(Honestly, it’s kind of beautiful in a way. She’s so fast. The form is perfect. You can tell she’s practiced it a lot.)"
    k "(But today that’s going to be her downfall.)"
#    {play thud noise}
#    {BZZT}
    n "What!"
    n "I don’t believe it. You dived right onto the floor. You went prone just as I lunged, and ducked under the blade."
    n "That’s ridiculous, but it worked."
    k "(I won’t be caught by those lunges anymore. This is it, it’s time for my counter attack!)"
    k "(Next I’m going to do something even more ridiculous.)"
    k "(Nana called this a blade, but that couldn’t be further from the truth.)"
    k "(A blade is designed for cutting and slicing things.)"
    k "(But in this game, you score so long as the button on the tip pushes against your opponent.)"
    k "(So in truth, this isn’t a blade at all!)"
    k "(It’s a javelin!)"
#    {woosh sound effect}
#    {BZZT}
    n "What the hell! You can’t throw your blade at someone, that’s against the rules."
    k "Sorry, but all I remember about the rules was being told that I score whenever my blade’s tip pushes against my opponent!"
    n " . . . "
    n "Ahahaha, I guess I can’t argue with that."
    k "3-9!"
    k "(This time, I’m going to counter that same lunge again.)"
    k "(I’ve got an absolutely ingenious strategy too. I’ll simply hold my blade in front of me, and then she’ll jump into it!)"
    n "Uwooooooooh!"
    k "(Here it is, her lunge! I’ll just hold my blade out like this and…)"
    k "(Wait, she’s not pointing the tip at me?)"
    k "(She just forced my blade out of the way!)"
#    {BZZT}
    n "Those were some fancy tricks, but they weren’t going to beat good old fashioned practice."
    n "GG. Well played."
    k "D-don’t think this means you’ve won!"
    k "We’re going again!"
#    {sword noises, fade into black. Stop sword noises, show outside the gym at sunset}
#    {Play https://www.youtube.com/watch?v=iawEZ2ejWm8&list=PLeKSx7u-0kRiJqH14dswC-lHh8Nuu0APx&index=22}
    hide hatfence
    hide nanafence
    show hat at left1
    show nana at right1
    k "(I feel so sweaty. I’m all out of breath. I think I’ve even got a bruise or two.)"
    k "(So why do I feel so good? It’s like there’s electricity popping off in my head.)"
    k "(Ah, Nana looks worn out too.)"
    n "Aaaaaaa, that was great. Wait there, I’ll be right back."
    hide nana
    k "(Eh? Where’s she going?)"
    k "(. . .)"
    k "(. . .)"
    k "(It’s been five minutes, where’d she go?)"
    show nana at right1
    n "Keiku, catch."
    k "(This is a can of juice?)"
    k "Is this for me?"
    n "Yep. I owe you for coming out at such short notice."
    n "That was a tonne of fun."
    k "I wasn’t even very good at it though."
    n "That’s fine, that’s fine! It doesn’t matter if you’re good or not. What matters to me is just that you gave it a go."
    n "I wouldn’t have been able to play at all if you weren’t here."
    n "Also, you’ve never done this before, so it would have been really embarrassing if I lost."
    k "Couldn’t you have just joined the fencing club if you wanted to do this?"
    n "No way. It’s like I said before. I can’t commit to any clubs other than the mahjong club."
    n "So I just do this stuff whenever I happen to have the time."
    k "Why’s the mahjong club the exception then?"
    n "Well, the mahjong club is a little less maintenance, and I could potentially make a career out of it."
    n "Also, I actually find it to be the most fun out of all the sports clubs. Also there isn’t a skateboarding club."
    k "Hmm, I see."
    n "Anyway, I have study to do now. I’ll catch ya later."
    k "(I guess it’s about time I got going too.)"
    k "(Hey, this juice is actually pretty good. She has good taste.)"
#    {Background transition to Keikus room at night, with crickets playing.}
#        {same as above. Never gonna date nana in my life ;_;}
    scene bg keikunight
    show hat
    k "(That was really tiring.)"
    k "(But I guess that’s a good thing.)"
    k "(With what happened to Watson, I’ve been struggling to sleep lately.)"
    k "(So tiring myself out before bed seems like a good strategy.)"
    k "(That was really fun. I’d like to play with Nana again soon.)"
    k "(I wonder if I could be as fit as her?)"
    k "(Nah, no way. I’m too uncoordinated.)"
    k "(. . .)"
    k "( z z z )"
    jump post_date1


label nana_date2:
    show hat
    k "(Time to head off to the library.)"
    k "(It seems weird that she’d want to meet me in the library, but I was planning on asking her to meet me there anyway.)"
    scene bg library
    show nana at right1
    show hat at left1
    n "Ah, Keiku!"
    k "Hey, Nana."
    n "Listen, I need to talk to you about something personal. Come over here."
    k "(What could it be? With the way she’s yanking me over, it has to be important.)"
    k "Alright, what’s up?"
    n "Keep your voice down. I don’t want people to overhear this."
    k "Okay, I gotcha."
    n "I need to talk to you about something weird."
    k "But why me specifically?"
    n "Well, it’s to do with a boy. I don’t think anyone else in the mahjong club has much experience with boys."
    n "Hinata is always too busy with her gardening to have a boyfriend, Xenia’s parents are way too strict to let her ever have a boyfriend, and Yui is… well, she’s Yui."
    k "Ah, well, I don’t actually have any experience with boys either. Do you?"
    n "You don’t? Ahhh, that’s a shame. Oh well, I’ll ask you anyway."
    n "And yeah, I totally have experience with boys. Tonnes."
    n "Anyway, it’s about this guy in the year below me. He’s another member of the student council."
    n "I think he really likes me."
    k "Oh, that’s great. Congratulations."
    n "No, that’s not great. I don’t like him at all."
    n "It’s not like he’s a bad guy or anything, but… he’s just not someone who could keep up with me, y’know?"
    n "It’s like, there’s no tension there, or excitement."
    k "Well, I’m sure it’ll be fine so long as you just tell him that you’re not into him."
    n "I know that’s what I probably should do, but I still don’t want to make him feel bad."
    n "Also, what if I just misread him, and he doesn’t actually like me at all? I think that’d be even worse."
    n "Like, imagine if you told someone that you didn’t have any romantic interest in them and they just said ‘yeah that’s cool, I wasn’t interested in you either.’"
    n "That’d just be way too embarrassing."
    k "(Hmmm. For someone who claims to have a lot of experience with boys, she sure doesn’t seem to have her finger on this guy’s pulse.)"
    k "Well, what makes you think he likes you?"
    n "Lots of little things. Like for example, I once made a joke about him going to the store and buying me an energy drink, and he actually did it."
    n "He said that he was planning on going down there to buy one for himself anyway, but I’ve never seen him drink an energy drink before in his life."
    n "Oh, and he’s always complimenting me when we’re doing student council stuff."
    n "Like ‘wow Nana, that’s an amazing idea.’ or ‘ah Nana, the way you think about that sort of thing is so smart.’"
    n "There was another time when there was a mugging in my neighbourhood, and he offered to walk me home. Do you think this guy likes me?"
    k "Yep, it definitely sounds like he likes you."
    n "Urgh. I really don’t want to have to go through letting him down. Like I said, he’s not a bad guy, but he’s certainly not someone I want to be with."
    k "Well, I think you should just tell him. It’s better to let him know early on, right?"
    n "Yeah. You’re right. I just gotta do it."
    n "Besides, I’ve got plenty of friends outside the student council and the mahjong club. I can probably just introduce him to one of them."
    k "If you have so many friends why’d you ask me?"
    n "Well, you just seem like a trustworthy person."
    n "Still though, thanks. Even though I was kind of sure that I needed to tell him, I feel like my head’s really cleared up now that I’ve heard someone else say it out loud."
    k "No worries. Now let’s play a game."
    n "Hoh? A game? What’ll it be?"
    k "(Hehe. I’ve picked out a game that this sports nut wouldn’t be able to beat me at.)"
    k "We’re going to be playing chess."
    n "Oh great, I love chess. I’m a big fan of it."
    k "(What the hell? That’s so out of character! I thought for sure I picked something I could win at this time.)"
    n "Don’t tell me you thought that I was just good at physical sports."
    n "I did join the mahjong club after all."
    n "Would you rather start as white or black? I’ll let you pick."
    k "No no, I challenged you, so you should pick."
    n "Well, if that’s the case, I pick black."
#    {Background transition to chessboard}
    k "(She sure seems confident in herself.)"
    k "(Shoot, I’m not actually that good at chess. I should have picked shogi instead.)"
    k "(I guess I’ll start with this pawn.)"
    k "(Next the other pawn.)"
    k "(. . .)"
#    {fade to black, then transition to chessboard in a late stage game with white winning.}
    k "(We’ve been playing for a while now.)"
    k "(I’m sort of surprised that I’m winning.)"
    k "(At the start she was so confident.)"
    k "(She takes so long to make all of her moves.)"
    n "Hmmmm… ummm... ermmmm…"
    k "(I feel like the last hour has just been spent staring at her face.)"
    k "(Her hair looks so nice and soft. I wonder what brand of shampoo she uses.)"
    k "(It’s kind of funny watching her think. She stares at the board so intensely.)"
    k "(As if staring at it hard enough will make a miracle.)"
    k "Nana, do you want to forfeit the game?"
    n "No way. I could still definitely turn this around."
    n "Winners don’t give up."
    n "Hmmmmm…"
    k "Alright, take your time then."
    k "(I should have brought a book or something.)"
    n "There, that’s my move. This will turn it all around."
    k "I see."
    k "I move my rook. Check."
    n "Oof. I didn’t notice that possibility."
    n "Hmmmmm."
    k "(She looks so surprised. Back to thinking then, I guess. Yep, just keep on staring at the board, I’m sure you’ll find some sort of way out.)"
    k "(...)"
    k "(Nana has such nice eyes. I wish my eyes were green, like hers.)"
    k "They’re so pretty…"
    n "Did you say something?"
    k "Ah! No, I was just talking about the, uh, the chess pieces."
    n "I see. Hmmmm, maybe this piece?"
    k "Nana, it’s getting kind of late. Shouldn’t we pack this up?"
    n "Eh? But it’s fun. I feel like I’ve almost figured out a way I could win."
    n "Maybe we could just leave it here and finish the game on monday?"
    k "(This girl…)"
    k "(Well, I can definitely respect not wanting to give up on something.)"
    k "Why don’t we call it a draw then?"
    n "No way. That definitely wouldn’t be fair on you."
    k "Well, what if I forfeit then?"
    n "No, that’d be even worse!"
    k "(Geh.)"
    k "(It seems like there’s only one way to solve this.)"
    k "Nana, I’m putting in a new rule."
    n "Huh? A new rule?"
    k "Yep. Each move now has a timer of ten seconds."
    k "10... 9... 8..."
    n "Aaaah! Maybe I could move the, wait, no, that’d put me in check, grh."
    k "7... 6... 5..."
    n "This pawn, I’ll move this pawn!"
    k "Okay, checkmate. GG."
    n "Ah, good game."
    k "Nana, how often do you play chess?"
    n "To tell you the truth, I’ve only ever actually played it once before."
    k "Huh? But you said you were a big fan of it."
    n "Well, of course. It’s more fun to play against someone who pretends they’re good at the game, right?"
    n "If I came out and said I didn’t know what I was doing, then it wouldn’t be interesting at all."
    n "Also, if I told you I was a total novice and somehow beat you, then you’d feel pretty bad about it, right?"
    k "I guess that is true."
    k "(So that’s just her way of trying to make things interesting, is it?)"
    k "Anyway, it’s time I headed off. Loser has to pack up the game. Laters."
    scene bg train
    show hat
    k "(Hmmm, that was a lot of fun.)"
    k "(Even if I spent most of the game just looking for something interesting to stare at while she thought about her moves.)"
    k "(I hope she’s able to let that boy down gently too.)"
    hide hat
    show hat at left1
    show nana at right1
    n "Oh hey, Keiku."
    k "Eh? Nana, are you on the same train line as me?"
    n "Yep. Not sure how I didn’t realise it until today though."
    k "Do you live around this area?"
    n "I think my stop is a bit further down the line than yours."
    n "By the way, thanks for hanging out with me this afternoon."
    n "I had a lot of fun. I’m sorry if I took a little long to make my moves in that game."
    n "If I’m playing a game, I just get wrapped up in it and want to do the best I can."
    n "I also really appreciate your advice from earlier. I don’t think I’m very good with emotionally sensitive stuff like that."
    n "If I told anyone else, I feel like they would have spread weird rumours around."
    n "But you just have an honest vibe to you, y’know?"
    k "Don’t worry about it. Talk to me about anything, any time you want."
    k "Anyway, my stop’s coming up. I’ll see you tomorrow at the tournament."
    n "Yep, see you tomorrow. Good luck!"
    scene bg keikunight
    show hat
    k "(Well, that was a lot of fun.)"
    k "(At the very least, I can definitely say I got back at her for that fencing match.)"
    k "(I really wasn’t expecting her to ask me for advice though. On the surface she seemed like the sort of person who’s super confident in herself and wouldn’t need advice.)"
    k "(Oh well. I better go to sleep soon.)"
    k "(. . .)"
    k "( z z z )"
