label xenia_date1:
    scene bg schoolfront
    show hat
    k "(I think I’ll call Xenia. She seemed like a fun person.)"
    k "(Also she’s rich. Gotta grab opportunities when you see ‘em.)"
    "*abababa* *abababa*"
    x "Hello, Xenia here."
#    {Play https://www.youtube.com/watch?v=gvFN1uB7qy0 /// not too sure about this one.}
#        {twewy music is based, but I imagine xenia with a more elegant ost. Something similar to https://www.youtube.com/watch?v=pdIKneM49GQ, https://www.youtube.com/watch?v=E4g5iC5NfK4 or something similar, or whatever in this playlist}
    k "Ah, are you um, are you busy?"
    x "Oh, Keiku. Yes, unfortunately I am quite busy right now."
    k "Ah, that’s okay then. Don’t worry about it."
    x "It’s fine. What were you calling about?"
    k "Ah, well, I was actually just calling to ask if you wanted to hang out today."
    x "Oh absolutely, I’d love to."
    k "Huh? Didn’t you just say that you were busy?"
    x "I was busy. But now I can use this as a reason to not be busy."
    x "My father's having some colleagues from his business over this afternoon, and he wants me to come in and make conversation with them and stuff."
    k "(I don’t understand why they’d need her around his work colleagues. I guess the world of business and wealth is just incomprehensible for people like me.)"
    x "So having you come over gives me a great excuse to get out of it. Come on over."
    x "Oh, but you’ll have to get changed first. My family won’t approve if I bring someone home wearing something like that hat."
    x "Please don’t be offended. It’s not something that’s up to me."
    k "(WOW.)"
    k "(This hat is a family heirloom! It’s been passed down for generations.)"
    k "(It’s not her fault though. I guess it can’t be helped.)"
    k "Alright, I’ll see you there."
#    {Scene transition, front of Xenias house. Kekumusume is using her bond outfit}
#    {Remember to add gate plus loud buzzing sound}
    scene bg xeniafront
    show xenia at right1
    show hatbond at left1
    x "Ah, I’m so glad you came over. Give me one second, I just need to explain to my father."
    hide xenia
#    {Xenias sprite disappears}
    k "(Hmm, I can vaguely hear them talking in the distance.)"
    x "Daddy, I brought a friend over from school. Sorry but do you mind if I skip on tonight so we can hang out?"
    who "Oh well, um, that’s..."
    x "Pleeeease daddy?"
    who "Well, I guess that’s fine then. We have to treat our guests well. Invite her in."
#    {Bring back Xenias sprite}
    show xenia at right1
    x "God, saying that felt disgusting."
    x "In any case, come in."
    scene bg xeniaroom
    k "(I followed Xenia inside, up the stairs, and into her room.)"
    k "(I can hear the faint mutterings of men downstairs.)"
    show xenia at right1
    show hatbond at left1
    x "Ah, thank you so much for coming. Please make yourself at home."
    k "Wow, this bedroom is huge. I can’t believe you have a couch in your room, and such a fancy TV."
    x "Yes, well, the family certainly comes with perks."
    k "What sort of work does your family actually do?"
    x "They’re big in the mahjong business. They sell luxury sets."
    x "The kind with gold bars for riichi sticks, chuns with rubies embedded in them, hatsus imbued with emerald, and hakus made of pure platinum."
    x "Ah, it’s so sickening, don’t you think? All a mahjong set needs is old fashioned wood."
    k "Hm, yeah, I think you might be right. It all seems sorta wasteful. Why do people even buy this stuff?"
    x "Status, of course. People buy it so that other people know they’re rich enough to afford it."
    x "In fact, those diamonds they embed in the eyes on the souzu birds aren’t even particularly rare. But people still buy them just because they’re expensive."
    k "Still, it must be nice to be rich even in spite of that."
    k "Like, if people wanted to buy useless junk from me for millions of dollars, I’d totally do it!"
    x "Hmmm, I suppose so. Having ‘stuff’ is nice indeed."
    x "Being able to afford things is nice. But there’s a lot of expectations that come with living in a family like this you know."
    x "I have to constantly be on guard in public, ‘for the good of the family image.’"
    x "Like, I can’t go outside wearing just a regular pair of jean shorts, it has to be a nice dress and of course it has to fit within the family definition of what’s ‘appropriate.’"
    x "Can you believe they actually get the maid to measure the length of the skirts I buy? I can’t even wear anything below the knee in summer."
    x "You know what I’d like to wear most of all? A swimsuit. Begone wetsuits."
    k "Wow, I guess being rich isn’t that great after all."
    x "I mean, being rich is pretty great, not gonna lie. It’s all the expectations I hate."
    x "Please don’t misunderstand me. I know that I’m in a very privileged position."
    x "You know, Keiku, I actually really appreciate you listening to me ramble on about this."
    x "If I told any of the other girls at school, they’d probably just be like ‘woooooow, look at the rich girl, complaining about all the MONEY she has. What a teeeeeeerrible dilemma!’"
    x "Enough about me though. What about you? What does your family do? I understand that you’re a mahjong detective, did you get the title from one of your relatives?"
    k "Yep, I come from a long line of mahjong detectives."
    k "But due to various circumstances, I’m the only one left."
    k "My parents died when I was younger, and my uncle looked after me."
    k "But he died recently. I don’t even know how or why."
    x "Ah, I’m sorry to hear that, and I’m sorry I brought it up."
    k "No, it’s fine. I don’t mind it."
    k "But listening to you talk, I have to guess there is a small upside. I can do whatever I want."
    x "Hah. I guess that is one way of looking at it."
    x "Enough of this depressing talk. Let’s do something fun. I’ve got some champagne hidden in the closet."
    k "Wow, your parents let you have champagne?"
    x "Emphasis on the hidden, dear."
    x "Cheers."
#    {Play a glug glug glug sound effect}
    k "Wow, this is, this is really something."
    k "(Honestly I can’t really tell the difference between this and the normal white wine that Watson used to let me sip. They both taste just as bitter.)"
    x "Heh. I honestly don’t even like the taste of this that much."
    k "You’re right, I feel like gagging it up whenever I drink it."
    k "Get me another glass anyway!"
#    {Glug glug glug sfx}
    hide hatbond
    show hatbondwast at left1
    k "Xenia, I think I get it now."
    k "Drinking with someone else really improves the flavour, y’know’what’I’m’sayin?"
    x "Indeed! In fact to add on to that, one might even say that the fact that we’re not allowed to do this makes it taste even better."
    k "Yeah, yeah! It’s like, this champagne is a uhhhh, what’s the word, a forbidden fruit."
    x "A fermented forbidden fruit."
    k "Yeah, yeah that’s it."
    k "You know, before I didn’t know why adults drank this stuff."
    k "But now I get it. I get it I get it. It’s because you drink this, and you just forget about all the things you were worried about."
    k "I should take some of this stuff before giving class presentations at school."
    x "You know, I’ve done that before actually. Works wonders."
    x "You have to find the right balance though. Too much and you’ll be stumbling all over your words."
    x "Although at the time you probably won’t even care."
    x "Frankly, I don’t know why people pay for therapists when we’ve got alcohol."
    k "Hahaha, yeah, this is way better than any counsellor."
    k "(Does Xenia have wobbly floorboards or something? I feel like I could tip over…)"
    "*thud*"
    k "Owwww, my head."
    x "Oh dear, I should have realised your tolerance would be lower than mine. You didn’t grow up on this stuff."
    k "No, no, I’m definitely fine!"
    x "You can barely walk. I’ll call for a taxi to take you home."
    x "It’s a shame we have to cut the night short, I’ve really had a lot of fun."
    k "Mmmmm, yep yep! I’ll see you later~ Buh bye!"
#    {Music stops}
#    {scene change, Keikus bedroom (night)}
#    {Play crickets noise}
#        {same as above}
    scene bg keikunight
    show hat
    k "(Aaaa, my head feels funny.)"
    k "(I feel like if I got out of this bed, the floor would just collapse underneath me.)"
    k "(That drink tasted so bitter and gross, but I still want a little more of it. Alcohol doesn’t make sense at all!)"
    k "(That really was a fun time though.)"
    k "(I was expecting her to be a little more like, uhhh, prim and proper.)"
    k "(I wasn’t expecting her to have such a fun rebellious side. I wanna hang out with her again later.)"
    k "(And maybe also get some more of that drink from her, hehehe.)"
    k "(. . .)"
    k "( z z z )"
    jump post_date1


label xenia_date2:
    show hat
    k "Alright. She said to meet her out the front of school."
    scene bg schoolfront
#    {Play https://www.youtube.com/watch?v=IDv7fPjHDxc0  /// really REALLY not sure about this but I can’t think of anything}
#    {Another potential option: https://www.youtube.com/watch?v=wL5hVgLET-U&list=PLKbO8VpACX_5U43g4JofYURa6D733iWsw&index=7}
#        {i suggest https://www.youtube.com/watch?v=E4g5iC5NfK4&list=PLox5jLt6-2odF5YZl8hlFyqiNy8dm_efc&index=6 or anything in that playlist}
    show hat at left1
    k "Hey Xenia."
    show xenia at right1
    x "Afternoon, Keiku. So where are we going?"
    k "I sort of just assumed that we’d go back to your place or mine."
    x "Hm, if that’s what you want to do then that’s fine with me."
    x "But my place is a little too stuffy. If we hang out there I’ll feel as if I’m being watched unless we just hang around in my room."
    x "Is there anything fun to do at yours?"
    k "(Aw, I kind of wanted to taste that champagne again.)"
    k "Hmmmmm."
    k "Nah. My place is pretty boring. All I have is a stack of dusty books."
    x "I see. Well then, why don’t we go into town instead."
    k "Alright then. Did you want to go anywhere in particular?"
    x "Yes, actually. Have you ever played baseball before, Keiku?"
    k "Huh, baseball?"
    x "Yep. There’s no better way to unwind than the batting cages. We’ll take the train."
    scene bg train
    "...."
#    {Fade bg to black, play some train noises (https://www.youtube.com/watch?v=xugNNnGhRIY) , fade out bg to batting cages}
#    {Play https://mega.nz/folder/f8EUHCIB#pOX8ovIQx0mQ9eFdiXf5UA/file/KwswRSgJ}
    scene bg batting
    show xenia
    x "Two cages and 100 balls for me and my friend please."
    "That’ll be $50."
    x "Right here."
    hide xenia
    show xenia at right1
    show hat at left1
    k "Oh, Xenia, I can pay for myself."
    x "Nonsense. I wouldn’t let a friend pay for their own batting cage. Especially when I’m the one who suggested it."
    x "Also, you didn’t answer me before. Have you ever played baseball before?"
    k "Just a little bit back in elementary school."
    x "I see. Let me give you a few pointers before we start."
    x "The most important thing is to make sure that you’re in a proper batting stance."
    x "First, make sure that your feet are a little wider than the width of your shoulders."
    x "Next, make sure that you’re bending at the knees."
    k "(Wow, she’s really getting right in there and grabbing and putting everything into place.)"
    x "Keep your arms near your back shoulder and always keep your eyes on the pitching machine."
    k "(I didn’t think a rich girl like her would be so passionately into something like baseball.)"
    x "Let me guess. You’re surprised that a rich girl like me is into something like baseball?"
    k "You’re not wrong. Great intuition there."
    x "It’s not like I’m a princess or something, you know. I do have normal hobbies."
    x "My dad loves baseball, so I grew up on watching it."
    x "Unfortunately, I never really had the chance to join a proper team, but I love these batting cages."
    x "Good luck!"
    k "(Alright, here comes the ball…)"
    "*woosh*"
    k "(Swing and a miss. It just went right past me.)"
    "*crack!*"
    k "(Sounds like Xenia just knocked one out.)"
    k "(Alright, here comes another one.)"
    "*thwack!*"
    k "(Oh wow, I actually hit it!)"
    x "Isn’t this fun, Keiku? When you hit the ball and the bat connects and makes that cracking noise, oh it’s such a rush."
    k "You’re right, this is pretty fun!"
    "*thwack*"
    "*crack!*"
    "*HOME RUN!*"
    k "(Her form is really amazing. Even a novice like me can tell that she has a perfect follow through on her swing.)"
    "*thwack*"
    "*crack!*"
    "*HOME RUN!*"
    k "So what sort of other hobbies do you have, Xenia?"
    x "I like video games a lot. I have to spend a lot of time at home during the holidays, so video games are an excellent way to pass the time indoors."
    "*thwack*"
    x "I also like the idea of camping a lot. Although I haven’t actually been able to do it since middle school."
    x "Going out on an extended camping trip would interfere with my family duties and my study a lot."
    x "They’d even object to a short overnight camp. Probably because they’d think it’d be dangerous or something."
    "*crack!*"
    x "How about yourself?"
    "*thwack*"
    k "Well, I used to be a part of the literature club. I do a lot of reading and a lot of my own writing."
    k "I wouldn’t say I’m particularly good at writing, but I’ve written a lot of mystery stories."
    "*crack!*"
    x "Interesting. You’ll have to show some of them to me sometime."
    x "I wouldn’t exactly consider myself a bookworm, but I do have an education in the classics."
    x "Mostly to make me appear cultured and smart to foreign business partners."
    x "I found a lot of them to be quite dull. But I found the Story of Oedipus to be very funny."
    x "The debauchery combined with the self-fulfilling prophecy was quite amusing."
    k "You know, you’re right. There’s something hilarious about it."
    k "The way that irony just twists the knife as far as it can go."
    k "It reminds me of something a certain fortune teller once told me. There’s no use fighting fate, so you might as well not waste the effort."
    x "Indeed! Macbeth is another great example of that sort of comedy."
    "*crack!*"
    k "‘No man of woman born may kill me!’"
    x "‘Oh, but I am no man of woman born!’"
    x "Imagine the look on Macbeth’s face when he realised how badly he screwed up."
    k "Yep. People underestimate how funny the classics can really be."
    "*crack!*"
    x "Oh, absolutely. Romeo and Juliet, for example. People have a very romantic view of that story."
    k "But that’s just because they usually haven’t read it!"
    x "Right? It’s a story about two dumb teenagers making stupid and hormonal mistakes."
    x "Can you imagine that? Eloping with the first hot person you see and dying for someone you only knew for a week?"
    k "Yeah, there’s no way you could truly fall in love with someone at first sight like that."
    k "If you think you have, you’re probably just crazy."
    x "Absolutely. Couldn’t be me!"
    k "Ah, but aren’t we also dumb teenagers?"
    "*bzzt* *bzzt*"
    x "Hold on, my phone’s ringing. One second."
    x "Yes, father? You need me at home right now? But I’m busy studying at school."
    k "(What a smooth liar.)"
    x "It’s urgent? I see then. I’ll be on my way."
    x "Ugh. It seems like our batting session will be cut short. What a shame."
    k "Ah, that really is a shame. I was enjoying our conversation."
    x "Well, my house is on the way to yours, right? We can keep talking on the train."
    scene bg train
    show hat at left1
    k "Hey Xenia, you said that you like camping, right?"
    show xenia at right1
    x "Hm? Yes, I love it."
    k "Why don’t you ever just sneak out at night and go camping then?"
    x "Well, that’d be very difficult. It’s not as if they have me locked up or anything, but there’s a very high gate, and it makes a buzzing sound when you open it."
    k "I see. What if you had a ladder or something like that?"
    x "A ladder? That’d stand out way too much."
    x "Although, I suppose that I could just put a chair in front of the gate and use that to climb over it."
    x "Do you want to try that?"
    k "(Wow, this is pretty sudden.)"
    k "(But yeah, camping sounds fun.)"
    k "Sure, let’s do it."
    x "Keiku, you are a blessing."
    x "My stop’s coming up. Let’s discuss the details later."
    k "Right. I’m sure we can work something out."
    k "Anyway, I’ll see you at the tournament tomorrow."
    x "Yep. Best of luck!"
    k "You too!"
    scene bg keikunight
    show hat
    k "(That was a lot of fun.)"
    k "(Or at least it was when I actually managed to connect the bat with the ball.)"
    k "(Xenia seems interesting. She’s full of surprises.)"
    k "(I’m looking forward to that camping trip. It’s crazy that she just agreed to it without a second thought.)"
    k "(She definitely needs to do something about her family though. How stiff can you be to not even allow an overnight camping trip.)"
    k "(But if we have to sneak around and do it in secret, then that’s just what we’ll do.)"
    k "(. . .)"
    k "( z z z )"
    jump post_date2
