label yui_date1:
    scene bg schoolfront
    show hat
    k "(Yui... she seemed like an interesting person. I think I'll give her a ring.)"
    "*abababa* *abababa*"
    y "...what?"
    k "(Oof, that seemed like a cold answer.)"
    k "It's, um, it's Keiku. I was just wondering if you'd want to hang out after school?"
    y "I'd like to do that. Yep."
    k "(Oh crap I didn't actually have any idea of where we'd go or what we'd do.)"
    y "Come to my house after school. I'll text you the address."
    k "(She's already inviting me to her house? That's a bit forwards, but I guess it's not an issue.)"
#    {Scene change, Yui's house}
    scene bg yuibedroom
    hide hat
    show yui at right1
    y "Hello. I'm glad you came."
    show hat at left1
    k "Well I'm glad you invited me."
    y "I want to show you something. Please come with me."
    k "Wait what? What are you showing me?"
    y "Something really good..."
    k "(I feel like I have no choice, she's just dragging me along.)"
    k "(What the hell, am I getting kidnapped? Is she about to show me something weird?)"
#    {BG change, Yui's room. Otaku room full of gunpla and gundam figures.}
    k "(Huh? Toys? Is this what she wanted to show me?)"
    y "Please sit down. We're going to watch the Mobile Suit Gundam movie trilogy."
    k "Wait, we're watching a movie now?"
    y "Did you want to do something else? You didn't mention any plans so I assumed it would be fine."
    k "Well I didn't actually have any plans so I don't see anything wrong with it."
    k "(Wait, did she say ‘trilogy’? She expects me to watch three of these movies?)"
#    {Gundam sound effects play muffled in the background. https://www.youtube.com/watch?v=5kTH6QROw6Q}
    k "(This is like a toy commercial for kids, isn't it?)"
    k "(But... this actually isn't that bad.)"
    k "(As much as I'm creeped out by this whole set up of hers, this movie is pretty good.)"
    k "(The characters are really interesting and the story is surprisingly dramatic.)"
    k "(. . .)"
    y "(. . .)"
    "*time passes*"
#    {Stop playing gundam sounds}
    k "That movie was actually really good."
    y "You liked it?"
    k "Yeah, I thought it was just going to be like a toy commercial, but I got really invested in the main character."
    k "(Although it is honestly still a toy commercial.)"
    k "(Wait a minute, is she staring at me? Has she been staring at me this entire time?)"
    y "Ah, that's really good. I wasn't sure if you'd like it."
    k "I really did! But, you're a little too close to me."
    y "..."
    y "Ah! I'm sorry! I'm really sorry. I just really wanted to see if you were enjoying it or not."
    k "Oh. Well, I guess that's fine then."
    k "(I mean it’s not fine, but I don’t want to spurn good intentions.)"
    y "Let's watch the next one now."
    k "Aaaah wait wait. There's no way I have time for all three of them on a school night."
    y "...oh, you should have said so. That's fine."
    y "By the way, I want to apologise to you."
    y "Yesterday in the club you said that you hoped we wouldn't expect much from you in the weekend tournament, and I said I wouldn't."
    y "I simply wanted to reaffirm that I wouldn't expect much from you because you told us not to."
    y "I didn't think that it would be something that could offend someone. Please disregard what I said. I expect you to do really well."
    k "(Wait, is she bowing?)"
    y "As a token of my apology, please accept this chocolate I bought."
    k "(This is a little weird, but I don't think she's malicious.)"
    k "Well I do think you're overreacting a bit, but I'll gladly accept it."
    y "Ah, I'm overreacting? I'm sorry."
    k "There’s no need to apologise twice."
    y "There's no need for that? Ah well, I'm sorry for that too."
    k "(Ah, this conversation seems like it’s just stuck in a loop.)"
    k "(Call up the scientists, we’ve discovered a perpetual motion machine.)"
    k "Well, there's no need to worry about it. See you tomorrow at school."
    y "Yep. Goodbye. Thank you very much for coming over."
    hide yui
#    {Scene change. Keikumusume’s bedroom at night. Play crickets https://www.youtube.com/watch?v=Olfg9KK_bmE}
    scene bg keikunight
    show hat
    k "(That was weird. What was up with all that staring and physically dragging me along?)"
    k "(She seems really nice though. I wouldn't mind hanging out with her again.)"
    k "(It's nice that she's so passionate about something.)"
    k "(This is also the first time in a long while that I’ve actually hung out with someone from school. It feels refreshing.)"
    k "(I feel like tonight is just a bit brighter than last night.)"
    k "(. . .)"
    k "( z z z )"
    jump post_date1


label yui_date2:
    show hat
    k "She said to meet her at her locker."
    scene bg lockerg
    show hat
    k "(Hmm, judging by what she texted me, her locker should be right here.)"
    k "(Looks like I got here first.)"
    k "(Wait, what the hell is written on her locker?)"
#    {play https://www.youtube.com/watch?v=icv-7qvFAHQ and cut boy in the windmill}

    k "(‘Autismo’)"
    k "(‘Spergqueen’)"
    k "(‘Living body pillow’)"
    k "(‘Retard’)"
    k "(This is awful. Who wrote all this?)"
    k "(I need to get rid of all this before she comes back.)"
    k "(Is there a sponge or anything like that around here?)"
    k "(No, there’s no time for that! I’m just going to have to use my shirt and some good old-fashioned spit.)"
    k "(I look like such a freak doing this. I’m pretty sure people are staring at me.)"
    k "(Looks like it’s slowly coming off.)"
    k "(Ugh, this might stain my nice white shirt.)"
    k "(Too late to worry about that now though.)"
    hide hat
    show hat at left1
    show yui at right1
    y "Keikumusume, what are you doing?"
    k "Ah!"
    k "(Aw shoot, she’s already here, and I’m not even halfway done!)"
    k "(I can still stop her from seeing it. I just need to cover the leftover text with my whole body.)"
    k "Ah, um, I was just waiting for you, Yui."
    y "I understand that. Why are you clinging to my locker so closely though?"
    k "Oh, clinging? This isn’t clinging. It’s just leaning. I just needed something to lean against."
    y "..."
    y "I see. Let’s go then."
    k "(Ah, she’s walking away. I’m so lucky that she didn’t need to take anything out of her locker.)"
    k "(I’ll just have to go to school early on monday and clean it off before she gets there.)"
    scene bg yuibedroom
    show hat at left1
    show yui at right1
    k "So what are we doing this afternoon, anyway?"
    k "(I ask, even though I’m the one who asked her to hang out.)"
    k "Are we watching the rest of those ‘gundam’ movies you like so much?"
    y "I thought about that. But I’d actually like to put that on hold."
    y "I chose the last thing that we watched together, so I think that this time it’s only fair that you choose what we watch."
    k "Ah, I guess that makes sense."
    k "Well then, there’s a murder mystery movie I’d really like to show you."
    k "It’s called ‘Cry of the Seacat’. It’s one of my favourite movies."
    y "Let’s watch that then."
#    {Start playing detective music. Either the umineko clarinet song or that one from the detective show that FE linked}
    k "It takes a little while to get going, but I think you’ll really like it."
    y "I see."
    y ". . ."
    y "Keikumusume, do you have a notepad and a pen that I could borrow?"
    k "Hm? Yeah, I have that in my backpack. Why?"
    y "This is a movie where you try to figure out who the killer is, right?"
    y "So I’d like to take notes."
    k "(Ah, she’s getting into this.)"
    k "Here you go."
    y "Hmm hmm."
    y "This chef seems suspicious, don’t you think?"
    k "Hehehe, I’ve already seen this and I don’t want to give out any spoilers, so I won’t say that he is or isn’t suspicious."
    k "(She’s writing on that notepad really intensely.)"
    y "This ‘closed room’ murder mystery is really tricky."
    y "Everyone's stomachs were left hanging open, but the doors are locked from the inside, and the killer wasn’t hiding inside the room after the door was broken down."
    y "As far as we know, there’s no hidden passageways into the room…"
    y "So it can’t have been possible for the killer to have cut their stomachs open."
    y "Maybe the killer snuck small explosives into everyone’s food, then one of the victims closed the door and locked the room from the inside."
    y "Then the small explosives detonated inside of them while the door was locked."
    y "It’s a very outlandish theory, but it’s the only explanation I can think of."
    k "Pffft, ahahaha."
    k "I’m sorry for laughing, it’s just that, y’know, ‘tiny bombs did it’ is such a funny explanation."
    y "I did say it was outlandish…"
    y "But yeah, it is pretty funny."
    k "(Ah, did she just smile? I feel like that’s the first time I’ve seen her expression change.)"
    y "Hmmm, maybe the killer for this next closed room was hiding behind a bookshelf when the detective broke down the door, and then escaped out behind the detective’s back."
    k "Very observant. I don’t think it’s a spoiler for me to say that you’re right there."
    y "Oh that was correct? Thanks. This is fun."
    k "(Watching her solve these is a blast. I’d like to see if she could solve one of my amateur works sometime.)"
    scene bg yuibedroomn
    show hat at left1
    show yui at right1

    k "Wow, Yui, I can’t believe you actually solved every single murder on your first try."
    k "I only got around half of them on my first go. Do you mind if I have a look at that notepad?"
    y "Sure."
    k "Wow, these notes are pretty extensive. You noticed a lot of clues I missed on my first watch."
    k "You’re actually really smart, Yui."
    k "(Aww, is she blushing a little?)"
    y "It’s nothing. I’m just good at taking notes and putting two and two together."
    k "Nah, you’re genuinely good at this. Maybe I should hand over my mahjong detective license to you."
    y "No thanks, I can’t take the smell of blood."
    y "Thank you for showing me this by the way. It was a lot of fun."
    y "Also, thanks for trying to rub all of that graffiti off of my locker."
    k "Urgh, did you notice that? I was hoping I could rub it all off before you saw it."
    y "Well, I didn’t see any of it myself."
    y "But your shirt is all smudged with ink, and you were hugging my locker really tightly."
    y "It wouldn’t have been the first time anyone has done that to my locker too."
    y "So I just connected the dots."
    k "Ah, I’m really sorry that I didn’t get rid of it all in time."
    y "Don’t be. I’m actually just glad that you tried to hide it from me."
    y "Usually people just pretend that it isn’t there, and I have to scrub it off by myself."
    y "So the fact that you not only tried to clean it up, but also tried to stop me from knowing that it was even there in the first place…"
    y "Well it means a lot. It really makes me happy."
    k "Aw, well, I think that it’s something any decent person should do."
    k "Why do they do that anyway? Did you make someone mad?"
    y "That’s just it. Most of the time I’m not sure if what I’m about to say is going to upset someone."
    y "To make matters worse, I often can’t tell if something I said made someone mad. Often I’ll need someone to tell me that I’ve made them mad."
    y "It’s not like I enjoy upsetting people. I hate it. Sometimes conversations feel like a minefield."
    y "Really what hurts me isn’t the words on the locker, but more so much that I don’t know who writes it."
    y "If I knew who wrote it, I could at least ask them what I did to upset them."
    k "I see."
    k "While it’s true that you might occasionally be a little too blunt for your own good, I don’t think you’ve done anything to upset people to the point where they’d be justified in writing stuff like that about you."
    y "Really?"
    k "Yeah. I think the people who wrote that are just being dicks because they think it’s funny."
    k "They’re nothing more than bullies picking on someone who they know can’t do anything about it. You shouldn’t worry about whether or not you did anything to upset them."
    y "Hm, that’s probably right."
    y "If you say it like that, it’s really obvious."
    y "It’s so frustrating though. Why couldn’t I see the logical connection here?"
    y "Why do they have to target me in particular? Is there something I’m doing wrong? Is there something about the way I talk?"
    y "I don’t see the logical thread here. I don’t understand what I’m meant to change."
    k "You shouldn’t even bother thinking about that stuff. They’re in the wrong, so their words are meaningless and should be ignored."
    k "Simple as pie."
    k "Anyway, it’s getting late, so I need to get going soon."
    y "Bye. And thanks again for everything you did today."
    y "I look forward to seeing you at the tournament tomorrow."
    k "Yep! Let’s do our best. See ya tomorrow."
    hide yui
    hide hat
    scene bg keikunight
    show hat
    k "(I’m glad that Yui liked ‘Cry of the Seacat’.)"
    k "(Seeing someone else get passionate about a story you love is a really nice feeling.)"
    k "(I didn’t realise she was so smart. She must have an iq of like, 180 or something.)"
    k "(I hope she puts it to good use in that tournament tomorrow.)"
    k "(Because that’s the only way the team will recover from my performance, hehe.)"
    k "(. . .)"
    k "( z z z )"
    jump post_date2
