label yui_date1:
    scene bg schoolfront with fade
    show hat
    play music "audio/yuidate1.mp3" fadeout 1.0 fadein 1.0
    k "(Yui... she seemed like an interesting person. I think I'll give her a ring.)"
    "*abababa* *abababa*"
    y "...what?"
    k "(Oof, that seemed like a cold answer.)"
    k "It's, um, it's Keiku. I was just wondering if you'd want to hang out after school?"
    y "I'd like to do that. Yep."
    k "(Oh crap I didn't actually have any idea of where we'd go or what we'd do.)"
    y "Come to my house after school. I'll text you the address."
    k "(She's already inviting me to her house? That's a bit forwards, but I guess it's not an issue.)"
#    {Scene change, Yui's house}
    scene bg yuibedroom with fade
    hide hat
    show yui at right1
    y "Hello. I'm glad you came."
    show hat at left1
    k "Well I'm glad you invited me."
    y "I want to show you something. Please come with me."
    k "Wait what? What are you showing me?"
    y "Something really good..."
    k "(I feel like I have no choice, she's just dragging me along.)"
    k "(What the hell, am I getting kidnapped? Is she about to show me something weird?)"
#    {BG change, Yui's room. Otaku room full of gunpla and gundam figures.}
    k "(Huh? Toys? Is this what she wanted to show me?)"
    y "Please sit down. We're going to watch the Mobile Suit Gundam movie trilogy."
    k "Wait, we're watching a movie now?"
    y "Did you want to do something else? You didn't mention any plans so I assumed it would be fine."
    k "Well I didn't actually have any plans so I don't see anything wrong with it."
    k "(Wait, did she say ‘trilogy’? She expects me to watch three of these movies?)"
#    {Gundam sound effects play muffled in the background. https://www.youtube.com/watch?v=5kTH6QROw6Q}
    k "(This is like a toy commercial for kids, isn't it?)"
    k "(But... this actually isn't that bad.)"
    k "(As much as I'm creeped out by this whole set up of hers, this movie is pretty good.)"
    k "(The characters are really interesting and the story is surprisingly dramatic.)"
    k "(. . .)"
    y "(. . .)"
    "*time passes*"
#    {Stop playing gundam sounds}
    k "That movie was actually really good."
    y "You liked it?"
    k "Yeah, I thought it was just going to be like a toy commercial, but I got really invested in the main character."
    k "(Although it is honestly still a toy commercial.)"
    k "(Wait a minute, is she staring at me? Has she been staring at me this entire time?)"
    y "Ah, that's really good. I wasn't sure if you'd like it."
    k "I really did! But, you're a little too close to me."
    y "..."
    y "Ah! I'm sorry! I'm really sorry. I just really wanted to see if you were enjoying it or not."
    k "Oh. Well, I guess that's fine then."
    k "(I mean it’s not fine, but I don’t want to spurn good intentions.)"
    y "Let's watch the next one now."
    k "Aaaah wait wait. There's no way I have time for all three of them on a school night."
    y "...oh, you should have said so. That's fine."
    y "By the way, I want to apologise to you."
    y "Yesterday in the club you said that you hoped we wouldn't expect much from you in the weekend tournament, and I said I wouldn't."
    y "I simply wanted to reaffirm that I wouldn't expect much from you because you told us not to."
    y "I didn't think that it would be something that could offend someone. Please disregard what I said. I expect you to do really well."
    k "(Wait, is she bowing?)"
    y "As a token of my apology, please accept this chocolate I bought."
    k "(This is a little weird, but I don't think she's malicious.)"
    k "Well I do think you're overreacting a bit, but I'll gladly accept it."
    y "Ah, I'm overreacting? I'm sorry."
    k "There’s no need to apologise twice."
    y "There's no need for that? Ah well, I'm sorry for that too."
    k "(Ah, this conversation seems like it’s just stuck in a loop.)"
    k "(Call up the scientists, we’ve discovered a perpetual motion machine.)"
    k "Well, there's no need to worry about it. See you tomorrow at school."
    y "Yep. Goodbye. Thank you very much for coming over."
    hide yui
#    {Scene change. Keikumusume’s bedroom at night. Play crickets https://www.youtube.com/watch?v=Olfg9KK_bmE}
    scene bg keikunight with fade
    stop music
    show hat
    k "(That was weird. What was up with all that staring and physically dragging me along?)"
    k "(She seems really nice though. I wouldn't mind hanging out with her again.)"
    k "(It's nice that she's so passionate about something.)"
    k "(This is also the first time in a long while that I’ve actually hung out with someone from school. It feels refreshing.)"
    k "(I feel like tonight is just a bit brighter than last night.)"
    k "(. . .)"
    k "( z z z )"
    jump post_date1


label yui_date2:
    show hat
    k "She said to meet her at her locker."
    scene bg lockerg with fade
    show hat
    k "(Hmm, judging by what she texted me, her locker should be right here.)"
    k "(Looks like I got here first.)"
    k "(Wait, what the hell is written on her locker?)"
    play sound "audio/yakumandealin.mp3"
#    {play https://www.youtube.com/watch?v=icv-7qvFAHQ and cut boy in the windmill}

    k "(‘Autismo’)"
    k "(‘Spergqueen’)"
    k "(‘Living body pillow’)"
    k "(‘Retard’)"
    k "(This is awful. Who wrote all this?)"
    k "(I need to get rid of all this before she comes back.)"
    k "(Is there a sponge or anything like that around here?)"
    k "(No, there’s no time for that! I’m just going to have to use my shirt and some good old-fashioned spit.)"
    k "(I look like such a freak doing this. I’m pretty sure people are staring at me.)"
    stop sound
    k "(Looks like it’s slowly coming off.)"
    k "(Ugh, this might stain my nice white shirt.)"
    k "(Too late to worry about that now though.)"
    hide hat
    show hat at left1
    show yui at right1
    y "Keikumusume, what are you doing?"
    k "Ah!"
    k "(Aw shoot, she’s already here, and I’m not even halfway done!)"
    k "(I can still stop her from seeing it. I just need to cover the leftover text with my whole body.)"
    k "Ah, um, I was just waiting for you, Yui."
    y "I understand that. Why are you clinging to my locker so closely though?"
    k "Oh, clinging? This isn’t clinging. It’s just leaning. I just needed something to lean against."
    y "..."
    y "I see. Let’s go then."
    k "(Ah, she’s walking away. I’m so lucky that she didn’t need to take anything out of her locker.)"
    k "(I’ll just have to go to school early on monday and clean it off before she gets there.)"
    scene bg yuibedroom with fade
    show hat at left1
    show yui at right1
    k "So what are we doing this afternoon, anyway?"
    k "(I ask, even though I’m the one who asked her to hang out.)"
    k "Are we watching the rest of those ‘gundam’ movies you like so much?"
    y "I thought about that. But I’d actually like to put that on hold."
    y "I chose the last thing that we watched together, so I think that this time it’s only fair that you choose what we watch."
    k "Ah, I guess that makes sense."
    k "Well then, there’s a murder mystery movie I’d really like to show you."
    k "It’s called ‘Cry of the Seacat’. It’s one of my favourite movies."
    y "Let’s watch that then."
    play music "audio/yuidate2.mp3" fadeout 1.0 fadein 1.0
#    {Start playing detective music. Either the umineko clarinet song or that one from the detective show that FE linked}
    k "It takes a little while to get going, but I think you’ll really like it."
    y "I see."
    y ". . ."
    y "Keikumusume, do you have a notepad and a pen that I could borrow?"
    k "Hm? Yeah, I have that in my backpack. Why?"
    y "This is a movie where you try to figure out who the killer is, right?"
    y "So I’d like to take notes."
    k "(Ah, she’s getting into this.)"
    k "Here you go."
    y "Hmm hmm."
    y "This chef seems suspicious, don’t you think?"
    k "Hehehe, I’ve already seen this and I don’t want to give out any spoilers, so I won’t say that he is or isn’t suspicious."
    k "(She’s writing on that notepad really intensely.)"
    y "This ‘closed room’ murder mystery is really tricky."
    y "Everyone's stomachs were left hanging open, but the doors are locked from the inside, and the killer wasn’t hiding inside the room after the door was broken down."
    y "As far as we know, there’s no hidden passageways into the room…"
    y "So it can’t have been possible for the killer to have cut their stomachs open."
    y "Maybe the killer snuck small explosives into everyone’s food, then one of the victims closed the door and locked the room from the inside."
    y "Then the small explosives detonated inside of them while the door was locked."
    y "It’s a very outlandish theory, but it’s the only explanation I can think of."
    k "Pffft, ahahaha."
    k "I’m sorry for laughing, it’s just that, y’know, ‘tiny bombs did it’ is such a funny explanation."
    y "I did say it was outlandish…"
    y "But yeah, it is pretty funny."
    k "(Ah, did she just smile? I feel like that’s the first time I’ve seen her expression change.)"
    y "Hmmm, maybe the killer for this next closed room was hiding behind a bookshelf when the detective broke down the door, and then escaped out behind the detective’s back."
    k "Very observant. I don’t think it’s a spoiler for me to say that you’re right there."
    y "Oh that was correct? Thanks. This is fun."
    k "(Watching her solve these is a blast. I’d like to see if she could solve one of my amateur works sometime.)"
    scene bg yuibedroomn with fade
    show hat at left1
    show yui at right1

    k "Wow, Yui, I can’t believe you actually solved every single murder on your first try."
    k "I only got around half of them on my first go. Do you mind if I have a look at that notepad?"
    y "Sure."
    k "Wow, these notes are pretty extensive. You noticed a lot of clues I missed on my first watch."
    k "You’re actually really smart, Yui."
    k "(Aww, is she blushing a little?)"
    y "It’s nothing. I’m just good at taking notes and putting two and two together."
    k "Nah, you’re genuinely good at this. Maybe I should hand over my mahjong detective license to you."
    y "No thanks, I can’t take the smell of blood."
    y "Thank you for showing me this by the way. It was a lot of fun."
    y "Also, thanks for trying to rub all of that graffiti off of my locker."
    k "Urgh, did you notice that? I was hoping I could rub it all off before you saw it."
    y "Well, I didn’t see any of it myself."
    y "But your shirt is all smudged with ink, and you were hugging my locker really tightly."
    y "It wouldn’t have been the first time anyone has done that to my locker too."
    y "So I just connected the dots."
    k "Ah, I’m really sorry that I didn’t get rid of it all in time."
    y "Don’t be. I’m actually just glad that you tried to hide it from me."
    y "Usually people just pretend that it isn’t there, and I have to scrub it off by myself."
    y "So the fact that you not only tried to clean it up, but also tried to stop me from knowing that it was even there in the first place…"
    y "Well it means a lot. It really makes me happy."
    k "Aw, well, I think that it’s something any decent person should do."
    k "Why do they do that anyway? Did you make someone mad?"
    y "That’s just it. Most of the time I’m not sure if what I’m about to say is going to upset someone."
    y "To make matters worse, I often can’t tell if something I said made someone mad. Often I’ll need someone to tell me that I’ve made them mad."
    y "It’s not like I enjoy upsetting people. I hate it. Sometimes conversations feel like a minefield."
    y "Really what hurts me isn’t the words on the locker, but more so much that I don’t know who writes it."
    y "If I knew who wrote it, I could at least ask them what I did to upset them."
    k "I see."
    k "While it’s true that you might occasionally be a little too blunt for your own good, I don’t think you’ve done anything to upset people to the point where they’d be justified in writing stuff like that about you."
    y "Really?"
    k "Yeah. I think the people who wrote that are just being dicks because they think it’s funny."
    k "They’re nothing more than bullies picking on someone who they know can’t do anything about it. You shouldn’t worry about whether or not you did anything to upset them."
    y "Hm, that’s probably right."
    y "If you say it like that, it’s really obvious."
    y "It’s so frustrating though. Why couldn’t I see the logical connection here?"
    y "Why do they have to target me in particular? Is there something I’m doing wrong? Is there something about the way I talk?"
    y "I don’t see the logical thread here. I don’t understand what I’m meant to change."
    k "You shouldn’t even bother thinking about that stuff. They’re in the wrong, so their words are meaningless and should be ignored."
    k "Simple as pie."
    k "Anyway, it’s getting late, so I need to get going soon."
    y "Bye. And thanks again for everything you did today."
    y "I look forward to seeing you at the tournament tomorrow."
    k "Yep! Let’s do our best. See ya tomorrow."
    hide yui
    hide hat
    scene bg keikunight with fade
    play music "audio/crickets.mp3" fadeout 1.0 fadein 1.0
    show hat
    k "(I’m glad that Yui liked ‘Cry of the Seacat’.)"
    k "(Seeing someone else get passionate about a story you love is a really nice feeling.)"
    k "(I didn’t realise she was so smart. She must have an iq of like, 180 or something.)"
    k "(I hope she puts it to good use in that tournament tomorrow.)"
    k "(Because that’s the only way the team will recover from my performance, hehe.)"
    k "(. . .)"
    k "( z z z )"
    jump post_date2

label yui_date3:
    scene bg maccastable
    show nana at left1
    n "Well, I’m off. Laters, guys."
    show hinata at right1
    h "Yep. See you all on monday."
    hide nana
    show xenia at left1
    x "I unfortunately have to get going too. Have a good sunday, everyone."
    hide hinata
    show yui at right1
    y "Actually, I have some free time as well. Keikumusume, do you want to go anywhere in the city?"
    hide xenia
    show hat at left1
    k "Hmmmmm."
    k "(Where’s a place in the city that Yui would enjoy?)"
    k "Are arcades still a thing?"
    y "They’re still around. I know a great one in this area."
    scene bg arcade with fade
    play music "audio/yuicitydate.mp3" fadeout 1.0 fadein 1.0
    #{Play https://www.youtube.com/watch?v=3ko-0jUzF4U }
    show hat at left1
    show yui at right1
    k "This is amazing. I didn’t think arcades with this many games were still a thing."
    y "Keiku, what do you want to play?"
    k "I’m kind of overwhelmed with all the choices."
    y "How about this one?"
    y "Alley Brawler 2: Turbo Charged: Hyperkinetic Fighting Champions Melee Edition."
    k "Okay, that sounds fun, let’s play each other in that."
    y "Ah, before we play, I should advise you that I’ve played this game a lot before."
    y "So it might be a little unfair if you haven’t played it."
    k "Nah, it’ll be fine, let’s go."
    y "Which character are you going to pick?"
    k "I’m going to pick the chibi cat with the big eyes because he looks cute."
    y "Are you sure? That’s a very low tier character."
    k "Yeah, I like his design so I’m picking him."
    "READY, FIGHT!"
    k "(Wow, she’s really good at using those fancy special moves and stuff.)"
    k "(I wonder how she managed to memorise all those inputs, they look super complex.)"
    k "(I guess I’ll just mash all the buttons.)"
    y "(. . .)"
    k "(. . .)"
    play sound "audio/ko.mp3"
    "K.O."
    k "(Wow, that worked?)"
    k "GG, Yui. Let’s pick out a different game."
    y "Good game, well played."
    y "To win your very first match, and with such a low tier character..."
    y "Keikumusume, I think you might be some sort of prodigy. That’s incredible."
    k "Hehehe, I definitely wouldn’t say that."
    y "Well, in any case, what should we play next?"
    k "Hmmmmm."
    k "Oh, what about this dancing game here?"
    y "Alright, then."
    k "(There’s no way I’ll lose to her in a dancing game.)"
    k "(Yui definitely doesn’t seem like the athletic type.)"
    scene bg ddr with fade
    show hat at left1
    show yui at right1
    k "(Yeah this is easy, I just have to follow the onscreen prompts.)"
    k "(Wait, this is getting a little too fast for me.)"
    k "(Ah, what the heck, how does Yui move so fast?)"
    k "Yui! How’re you hitting perfect timing on every step like that?"
    y "Oh, you know."
    y "I just happen to have memorised most of the songs in this game."
    k "This is way too fast!"
    play sound "audio/thud.mp3"
    "*Thud*"
    y "Ah, Keiku, are you okay? Let me help you up."
    k "Oh, I’m fine. I think I just tripped over my own feet."
    y "You’re not injured anywhere, are you?"
    k "No way, it was just a little fall."
    y "Good. I’m really glad you’re alright."
    k "Thanks, but I’m definitely not suited for this game."
    k "Also, since when were you such a good dancer? I didn’t know you were so athletic."
    y "I wouldn’t say that I’m a particularly good dancer. I’ve just played this game a lot."
    y "I actually do swim a lot though. There’s something very relaxing about it."
    y "Now what should we play next?"
    k "Ah, I’m actually all out of change."
    y "That’s a shame, so am I."
    k "Is there anywhere else in the city you’d like to go then?"
    y "Yep. There’s a model store I wanted to stop by at on my way home. But if you’re not interested in that sort of thing it’s fine."
    k "Let’s go then. I’m interested in whatever it is that you’re interested in."
    scene bg modelstore with fade
    show hat at left1
    show yui at right1
    k "Wooooow, there’s so many toys here."
    y "They’re called models..."
    k "Oh, so those robot toys you have at home, you have to build them? They don’t just come out of the box?"
    y "Yep. Look inside one of the boxes and you can see how many pieces there are. Some of these kits need to be painted as well."
    k "Oh, that’s actually sort of cool. It looks pretty complicated for a toy. I bet you’d have to be really smart to put something like that together. There’s so many small parts."
    y "It’s not really that complicated. It’s not unlike legos. People just think it’s hard because there’s lots of parts to it."
    y "There’s models for beginners as well. Ones with just a few parts."
    k "Ah, look at this one! It looks like a teddy bear, but it’s also a robot."
    k "I didn’t think that robots could look cute, but this one really does look cute."
    k "It’s the sort of thing you want to pick up and take home. It even has a little bow on it. Hau~!"
    y "Yep, the bearguys are cute."
    k "Is there an anime about them? I’d like to watch that."
    y "Unfortunately, no."
    k "Awww. So, does this one require assembly, too?"
    y "Yeah. But it’s pretty easy. You just snap it together."
    k "Hmmmm, you say that, but I think I’m just a little klutzy for it."
    k "That’s a shame."
    k "I’m actually kind of curious, Yui. What is it about this stuff that makes you like it so much?"
    k "I mean, I can definitely see the appeal, but you’re really into it."
    y "Hmmmmm."
    y "I think it might just be because robots are easy to understand."
    y "People have so many different faces, but a robot just has the one."
    y "That simplicity is comforting to me."
    y "I also find the process of building these models to be very calming."
    y "Each piece slots neatly into the next with a logical connection."
    y "You might say it’s a zen-like experience."
    k "I see. That’s a deeper explanation than I was expecting. I thought you were just going to say that they look cool."
    y "Well, there is that, too."
    k "Anyway, did you find what you were looking for?"
    y "Yep. It’s a new kit, exclusive to this store."
    y "It’s got a complete inner frame that allows for full scale transformations. It’s really amazing."
    k "(I don’t know what that means, but I’m happy she’s happy.)"
    y "I’m just going to go ring this up and we can go."
    scene bg trainstation  with fade #to change
    show hat at left1
    show yui at right1
    k "Yui, you’re on a seperate train line to me, right?"
    y "Yep, mine goes in the opposite direction."
    k "Well, I guess this is see you later then."
    k "I had a lot of fun today. Even if I did dash our chances of a victory."
    y "It’s fine. Maybe our team really is just cursed. You can’t do anything about that."
    y "Thanks for taking me to the arcade afterwards, I had a great time."
    y "Keikumusume, will you be busy tomorrow?"
    k "Nope. Why?"
    y "Would you like to meet up again?"
    k "Of course! Just text me a time and place and I’ll be there."
    y "Thank you. I’ll see you tomorrow, then."
    scene bg keikunight with fade
    stop music
    show hat
    k "(Today's tournament was a lot of fun.)"
    k "(Especially watching Yui play. The way she thinks is so fascinating.)"
    k "(Hanging out afterwards was fun, too. I had no idea Yui could groove like that.)"
    k "(Just a few days ago, I wouldn’t have imagined that I’d have become so close to someone.)"
    k "(I want to wake up soon so that I can see her again...)"
    k "(. . .)"
    k "( z z z )"
    jump yui_final

label yui_final:
    scene bg keiku with fade
    "*Kiki kanri!* *Kikikanri!*"
    show hat
    k "Yawwwwwwn."
    k "(That’s strange, I don’t feel at all tired today.)"
    k "(That’s right. Because today I have something to look forward to.)"
    k "(Somehow, having something to look forward to makes it a lot easier to get out of bed.)"
    k "(Before meeting Yui, I would have just laid about in bed until 1pm.)"
    k "(I might not have even eaten breakfast.)"
    "*Abababa* *ababababa*"
    k "(Ah, there’s her text now.)"
    y "Keikumusume, do you mind if I come over to your house soon? Or you to mine. Whichever one is more convenient."
    k "(Well, I guess it’s fine for her to come to mine. Saves me the train fare.)"
    k "(Text, sent.)"
    k "(I guess I’ll just read until she gets here.)"
    k "(. . .)"
    k "(. . .)"
    k "(Ah, what the heck? I feel weird. As if I can’t just sit still and wait for her.)"
    k "(It feels like there are ping-pong balls in my brain again, only even more intense.)"
    k "(I guess that just means I’m really looking forward to this, then.)"
    k "(It’s not a bad feeling.)"
    "time passes"
    "*knock knock*"
    play music "audio/yuidate3.mp3" fadeout 1.0 fadein 1.0
#    {play https://www.youtube.com/watch?v=jI2dAzEAzzk&list=PLE234F313FF53A39C&index=20 }
    k "(Ah, is that her?)"
    k "Yui, is that you? Come on in."
    hide hat
    show hat at left1
    show yui at right1
    y "Hello, Keikumusume."
    k "(That’s weird. She’s got bags under her eyes.)"
    y "Please forgive me if what I’m about to say is a little awkward."
    y "It may come off as weird for me to do this. Maybe you don’t consider us to be good enough friends for a gift to be appropriate."
    y "But I want to give this to you."
    k "Is this..."
    k "Is this that toy bear that I was looking at with you yesterday?"
    y "Yep."
    k "Thank you! It’s so cute!"
    k "It looks really well made, too. The paint is so bright and it looks so detailed."
    k "Ah, you even painted a little love heart onto it, that’s so cuuuuute."
    k "Wait, did you stay up all night to make this?"
    y "Yep. I also made lunch."
    y "See? I made us lunch boxes."
    k "(Oh wow, she even cut up the apple slices so that they all have bunny ears. That’s adorable.)"
    k "Ah, you shouldn’t do that. I really like it, but you should think more about your health. I really wouldn’t want you to get sick or something."
    y "That’s fine. I’m just happy knowing that something I built made you happy."
    y "I wanted to do something for you since the incident with my locker."
    y "No one has ever done anything like that for me."
    y "Keikumusume, I really enjoy being around you."
    y "With other people, I can’t understand what they’re thinking. It makes it very hard to communicate."
    y "But with you, it’s as if everything is right there on your face."
    y "I don’t have to worry about saying something that will accidentally upset you."
    y "I don't feel anxious around you at all. I can understand you without struggling and worrying about misinterpreting you."
    y "So, I’m very grateful to have met you."
    k "You know, Yui, when I first met you, I honestly did think you were a little bit weird."
    k "But I’m really glad that I got to know you instead of brushing you off."
    k "Because I can tell that you’re always trying your best for everyone."
    k "I don’t mind that you’re a little quiet either. I actually find it really relaxing to be around you."
    k "Yui, can I say something a little awkward, too?"
    y "Go ahead."
    k "(How am I meant to phrase something like this?)"
    k "(I just need to say it. There’s no use beating around the bush.)"
    k "I think I love you, Yui."
    y ". . ."
    y "Did you say that you love me?"
    k "Ah, I’m sorry, I shouldn’t have said that."
    y "No, it’s okay. I’m just a little shocked. I never thought that anyone would say something like that to me."
    y "Keiku, I love you too."
    k "That’s great! I’m so glad you feel the same way."
    k "(Kyaaa! I feel so dizzy.)"
    k "(She loves me too!)"
    y "Keiku, do you mind if I get a little closer?"
    k "Get as close as you want."
#    {Display CG art for Yui}
    scene bg yuiart with fade
    $ renpy.pause (10.0)
    k "(She’s lying on top of me now. It’s like she’s burying herself in my chest.)"
    k "(It feels so warm.)"
    y "Do you mind if we just stay like this for a while?"
    k "Of course not. I wouldn’t mind staying like this forever."
    k "(Her fingers are interlocked with mine...)"
    k "(I don’t think either of us needs to say anything else now.)"
    k "(I’d love to just lie with her like this for the rest of time.)"
    k "(Nothing else needs to be said or done.)"
    k "(I don’t need to say anything to understand her, and she doesn’t need to say anything to understand me.)"
    k "(I think that’s the best communication there is.)"
    k "(We can stay like this forever.)"
    scene bg black with fade
    stop music
    k "(Since I joined the mahjong club, my life has become a lot brighter.)"
    k "(In just one week, I’ve not only made friends, but also met a lover.)"
    k "(I’m not sure how long me and Yui will last.)"
    k "(Once we graduate, she’ll probably go use her 180iq at some high class university, and I’ll be super busy working for the MCD.)"
    k "(But that’s fine. That’s sort of just how high school relationships go.)"
    k "(For now, I want to treasure this year with her.)"
    k "(I need to visit Watson’s grave again soon. In a way, he taught me to not close myself off. I need to thank him for that.)"
    k "(I can’t go back in time and spend more time with him. But I’ll be sure to treasure the time I have with Yui now.)"
    jump post_date3
